language: cpp

matrix:
  include:
    - name: windows
      os: windows
     # MSVC is already installed on Travis, keep it here just in case we need to use it later
     #install:
     #- choco install visualstudio2017-workload-vctools -y --package-parameters "--no-includeRecommended --add Microsoft.VisualStudio.Component.VC.x86.amd64 --add Microsoft.VisualStudio.Component.Windows10SDK"

before_install:
  - PATH=${PATH}:${PWD}

before_script:
    - ./bootstrap-vcpkg.bat
    - ./vcpkg.exe install eigen3
    - ./vcpkg.exe export eigen3
    

script: shell
